
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.6
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: fix-encoding-pragma
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-added-large-files
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [--max-line-length=88]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

