repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system

      - id: black
        name: black
        stages: [commit]
        language: system

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
