[tool.black]
line_length = 88
target-version = ['py37']

[tool.isort]
profile="black"
multi_line_output = 3
line_length = 88
include_trailing_comma = true

[tool.flake8]
max-line-length = 88

[tool.autopep8]
max-line-length = 88


